### PR TITLE
Add Sorting Functionality for Selection Parameters 

### PR DESCRIPTION
**Pull request by CpdnCristiano**
This change improves usability, especially when there are many devices or users, as finding specific entries becomes challenging without sorting options. With this functionality, Traccar users can quickly and easily locate devices or users in large lists.

### CODE REVIEW

**Comment by tananaev** [comment]
I think sorting it on the server side probably makes more sense.

**Comment by CpdnCristiano** [comment]
I can do this. Should I classify by default, or should I create a filter, for example: `devices?sort=name`?

**Comment by tananaev** [comment]
It's probably fine to sort by default. This should be done through the database query.

**Comment by CpdnCristiano** [comment]
I will implement sorting on all endpoints, and issue #1272 requested sorting of groups. Then, I will make a PR.

**Comment by tananaev** [comment]
I would recommend starting with one endpoint, so we can review the implementation before applying it to everything.

**Pull request closed without merging**
