### PR TITLE
Adds Pushover user attributes

### PR DESCRIPTION
**Pull request by lzkill**

### CODE REVIEW

**Comment by tananaev** [comment]
You should only change `en.json`. All others are generated from Transifex.

https://www.transifex.com/traccar/traccar/

**Comment by lzkill** [comment]
Nice! Since I've already translated all files, is there anything I still need to do?

**Comment by tananaev** [comment]
You need to remove all localization from the PR. It doesn't work like that. Those files will be overwritten.

**Comment by lzkill** [comment]
> You need to remove all localization from the PR. It doesn't work like that. Those files will be overwritten.

Hi Anton. Do I have to do anything else here? This PR is supposed to be merged along with [traccar/pull/4908](https://github.com/traccar/traccar/pull/4908). The main idea is to allow Pushover notifications to be configured per user just like Telegram.

**Comment by tananaev** [comment]
I still see all the localization files. You have to revert those changes.

**Pull request merged**
