### PR TITLE
Rewrote tools/minify.sh;

### PR DESCRIPTION
**Pull request by jon-stumpf**
I was not familiar with Sencha. In learning how it works and how it installs, I rewrote the shell script based on a common structure that I have used throughout my career.  If you find it useful, please feel free to merge.

### CODE REVIEW

**Comment by tananaev** [comment]
Unfortunately it doesn't work like the old script. I can run the old one from anywhere. For example from Traccar root:
```
traccar-web/tools/minify.sh
```

**Comment by jon-stumpf** [comment]
I thought I handled that case.  I will fix it.

**Comment by jon-stumpf** [comment]
Please provide me the context that you experienced the error.  I reran my tests and I am able to run the command from anywhere.  I believe the error you are experiencing has to do with the location of SENCHAROOT and I will need to check some other things in the script.

Please provide me the PWD where you run the script and the absolute path of where your SENCHAROOT is.

Thanks.

**Comment by tananaev** [comment]
I didn't specify any locations. I took your file and ran command that I provided earlier.

**Comment by jon-stumpf** [comment]
I understand that you did not specify a location.  I modeled the condition and ran a different test.  I believe I covered the default behavior correctly.  Please try again.

**Comment by tananaev** [comment]
Now the problem is with CMD path:
```
$ tools/minify.sh 
tools/minify.sh: line 59: tools/../../../Cmd/sencha: No such file or directory
```

I think I'll just leave existing script for now. We can keep pull request open in case someone else want to use more advanced script.

**Comment by jon-stumpf** [comment]
This is why I don't like relative paths.  :)

I see that I made an assumption that is not valid in your default case.  I install third-party software under /opt and use very specific rules from the LSB.  I eliminated the assumption.

If you would just indulge me, I would like to understand what I am not understanding about how you installed Ext.js and Sencha Cmd.  Can you tell me the following paths in your environment?

1. The absolute path of **traccar-web/tools/minify.sh**.
2. The absolute path of the Sencha **ext-6.2.0** directory.
3. The result of $(**which sencha**).

Thank you.

**Comment by tananaev** [comment]
I only installed CMD. It's in my PATH. ExtJS itself is just a folder next to Traccar repo folder.
```
$ which sencha
/Users/tananaev/bin/Sencha/Cmd/sencha
```

**Comment by jon-stumpf** [comment]
Thanks.  My last commit assumes that "**sencha**" is in the PATH rather than use an absolute path.

**Pull request closed without merging**
