### PR TITLE
Add notification snackbar

### PR DESCRIPTION
**Pull request by lucasleite01**
Notification snackbar added when some event arrives from websocket:

snackbar

### CODE REVIEW

**Comment by tananaev** [comment]
Why are we replacing this?

**Comment by lucasleite01** [comment]
I couldn't see any notification on screen when events arrived even with the `displayNotifications` function. Perhaps some misconfiguration in my environment?

**Comment by tananaev** [comment]
Have you enabled permissions?

**Comment by lucasleite01** [comment]
Notification permissions on Traccar server? Yes.

**Comment by tananaev** [comment]
Not sure why it doesn't work then. You should probably investigate it instead of re-implementing it.

**Comment by lucasleite01** [comment]
Right. I'll do that and if I don't find anything I'll close this PR.

**Pull request closed without merging**
