### PR TITLE
Add camper device category

### PR DESCRIPTION
**Pull request by TheZoker**
This PR adds a new device category called `Camper`. 

Screenshot of a tracker with that category:
image

### CODE REVIEW

**Review by tananaev — COMMENTED** [review]
1. What is the source of the image?
2. Please don't include string translations. You should only include English.

**Comment by TheZoker** [comment]
The source is here:
https://www.iconpacks.net/free-icon/camper-van-13375.html

It does not require credit or similar.

I removed the translations

**Comment by tananaev** [comment]
Can you please provide a screen shot of the map with another category next to is, so we can compare.

**Comment by TheZoker** [comment]
Here are three in a row:

image

**Comment by tananaev** [comment]
It doesn't look very consistent with the style. Some very small details. And wheels are in different style.

**Comment by TheZoker** [comment]
Alright I will look for a different file. Where do the original icons come from? Maybe that will help to find something. 

It needs to be a icon without credit, right?

**Comment by tananaev** [comment]
Yes, it needs to be without credit. I believe the original icons are from Icons8.

**Comment by TheZoker** [comment]
Alright so this should be the car file:
https://icons8.de/icon/set/car/material-rounded

And this would be the camper:
https://icons8.de/icon/set/camper/material-rounded

Would that work for you?

**Comment by tananaev** [comment]
I don't think those are links to specific image.

**Comment by TheZoker** [comment]
Ah sorry, here is the correct link:
https://icons8.de/icon/93858/wohnwagen-campingplatz

https://icons8.de/icon/85104/auto

**Comment by TheZoker** [comment]
Here is the new preview:

image

Next to the camper I also added a caravan.

**Comment by tananaev** [comment]
Wait. Are we adding two icons now? I think that's a bit of overkill.

**Comment by TheZoker** [comment]
A friend that also uses the software for his caravan/trailer asked me if I can add this icon as well. But I can also remove it again

**Comment by tananaev** [comment]
I think one icon is enough.

**Comment by TheZoker** [comment]
Done, second icon is removed again

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
