### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by tgroshon**
Several important packages were outdated enough to have transient deps
with security vulnerabilities. This patch upgrades key packages and
makes config adjustments to support them.

### CODE REVIEW

**Comment by tgroshon** [comment]
@tananaev this is my first step to contributing more features to the `modern` rewrite.

Related to this change, how are your feelings on including the `package-lock.json` in the git repo?  It's a fairly common practice, but I saw that file was specifically ignored in `.gitignore` so I wanted to get your thoughts before asking to change it.

**Comment by tananaev** [comment]
Have you tested that it works? I remember I tried updating and there were some conflicts. Does websocket and API proxy work correctly?

As for lock file, I would prefer to leave it out, at least for now during active development.

**Comment by tgroshon** [comment]
I did have to update the `proxy` key which changed on newer versions of `react-scripts` and add the `browserslist`.  I compared a build of my branch with current `modern` and they seem to behave identically:

1. Successful `npm start`
2. No additional console errors
3. Login works (fetch request to `/api/session` on login and main pages work) to my local traccar
4. WebSocket connects and pulls positions from my local traccar

So the upgrade seems good.

For the lock file, no problem. I will leave it out.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
