### PR TITLE
Add speed to events report

### PR DESCRIPTION
**Pull request by victorferreira**
Now the events report shows the speed limit and the registered speed whenever a vehicle passes the speed limit.

### CODE REVIEW

**Comment by tananaev** [comment]
@Abyss777, do you see any issues here?

**Comment by Abyss777** [comment]
Yes, there are warnings if event does not contain such attributes. I would implement like this:
```javascript
        renderer: function (value) {
            if ('speedLimit' in value) {
                return Traccar.AttributeFormatter.speedFormatter(value['speedLimit']);
            }
            return null;
        }
``` 

If we will use them somewhere else (like events panel) it is better implement it like calculated fields, for now it is fine.

**Comment by tananaev** [comment]
I also vote for calculated fields. Seems like a cleaner solution.

**Comment by Abyss777** [comment]
I would more say universal solution, like we do for Route report, add "known" events attributes as hidden columns. But there would be some work...

**Comment by tananaev** [comment]
Hmm.. yes, completely forgot about that. That would be much better and more consistent.

**Pull request closed without merging**
