### PR TITLE
improving italian translation + add missing key in en.json

### PR DESCRIPTION
**Pull request by arkanoid87**
syncing keys between italian and english json
matching capitalization strategy of en.json

### CODE REVIEW

**Comment by tananaev** [comment]
The "missing key" is the one we already removed. As for localization, you shou do it via Transifex:

https://www.transifex.com/traccar/traccar/

**Comment by arkanoid87** [comment]
my fault! thanks for the link

**Comment by arkanoid87** [comment]
Italian translation 100%

**Comment by tananaev** [comment]
Thanks. It will be picked up with the next official release.

**Pull request closed without merging**
