### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spacecabbie**
Added steps to clone partial repo (aka modern dir only)

### CODE REVIEW

**Comment by tananaev** [comment]
This is not really a necessary part to run the web app, so I don't want to overcomplicate readme doc with it.

**Comment by spacecabbie** [comment]
> This is not really a necessary part to run the web app, so I don't want to overcomplicate readme doc with it.

I do understand your point. Just wanted to let as much people able to test it including the not so technical abble. since this is the development dir it could be replaced with the proper readme when pushed as release.

**Comment by tananaev** [comment]
Yeah, but even with development I don't really see any good reason for it. What problem does it solve?

**Comment by spacecabbie** [comment]
None whatsoever,

Your looking at it from programming perspective and then yes it has no value. But to help a user it allows quick testing which in turn adds to feedback and bug reporting.

Like myself for example I consider myself in between programmer/user. It took me a while to figure this out, I don't work daily with git etc.
Now i have it running i can add basic options to the template. and contribute even though it's a little. 

I get your point though leaving it up to you ofc.

**Comment by tananaev** [comment]
Why do you want to partially clone repo instead of full repo? I still don't understand it.

**Pull request closed without merging**
