### PR TITLE
Created mostly used stores

### PR DESCRIPTION
**Pull request by mail2bishnoi**
Hi Anton,

I have created mostly used stores that can be used in subsequent PRs. Please review and suggest improvements.

### CODE REVIEW

**Review by tananaev — COMMENTED** [review]
I don't think we need all those stores. I would prefer to keep global stores to a minimum.

**Comment by mail2bishnoi** [comment]
Hi Anton,

I have filtered out some of them. I think below mentioned should be there-
1. groups
2. drivers
3. maintenance

about rest of them I'm not sure. Please tell which stores I should keep and which should be removed.

**Comment by tananaev** [comment]
Why do we need maintenance there?

**Comment by mail2bishnoi** [comment]
In the Events report we have Maintenance Id column. To format that we need Maintenance.

**Comment by tananaev** [comment]
OK, let's cut down to those 3 for now.

**Comment by mail2bishnoi** [comment]
Done.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
