### PR TITLE
Add typescript

### PR DESCRIPTION
**Pull request by RodolfoSilva**
Hey @tananaev I'm sending this PR to add typescript support, if you accept this, I'll send a new PR with all others files converted.

### CODE REVIEW

**Comment by tananaev** [comment]
I'm not sure about typescript. Also, you haven't provided any arguments.

**Comment by RodolfoSilva** [comment]
Right, 
* Typescript will provide a better developer experience.
* Prevents some bugs, because now we can have types to help avoid typos and other things.
* Documentation, with typescript is very easy to understand what we need for execute a function or whats is the data structure of properties or entity.
* Type checking in compilation time.

**Comment by tananaev** [comment]
For now I'm not convinced that it's a good idea. It adds another layer.

**Comment by LWlook** [comment]
This greatly reduces the likelihood of errors and I would love to see Typescript in such a project. I would never again program in a not typed language.
And it don't really adds another layer (depends on what you see as layer). It only helps the programmer to program, in the output typescript no longer occurs as it is compiled.

**Pull request closed without merging**
