### PR TITLE
Inputs fix

### PR DESCRIPTION
**Pull request by dkyeremeh**
## Summary
1. Addresses issues with inputs #869
2. Updated styling of disabled buttons
3. Updated padding of grids containing inputs to accommodate new input margin

@tananaev Kindly let me know if I've missed any part the inputs were not showing correctly

Screenshot 2021-06-29 at 6 20 38 AM
Screenshot 2021-06-29 at 6 21 06 AM

### CODE REVIEW

**Review by tananaev — COMMENTED** [review]
One tiny thing I noticed is that label text start is not aligned with error message start. It's not an issue with default component because of the field background, but it looks a bit odd with our design. Can we fix it?

**Comment by dkyeremeh** [comment]
Nice catch. Will address it

**Comment by dkyeremeh** [comment]
@tananaev done

**Comment by tananaev** [comment]
Merged, thank you.

**Pull request merged**
