### PR TITLE
Added report title to all the reports

### PR DESCRIPTION
**Pull request by mail2bishnoi**
Hi Anton,

I have added the title to all the report tables. Please review the code once and suggest improvements.

With this, I would like to work on chart reports. Would you like to recommend any chart library?

Thanks.

report-title-screen

### CODE REVIEW

**Comment by tananaev** [comment]
What is the value in this? And if we do add title, it should probably go in the toolbar.

**Comment by tananaev** [comment]
Haven't investigated charts, but let's discuss before you start implementation.

**Comment by mail2bishnoi** [comment]
> What is the value in this? And if we do add title, it should probably go in the toolbar.

Because sometime I confuse that which report I am looking at, and I have to look at url. Thats why I think its better to add a report heading.

By toolbar you mean page's title?

**Comment by tananaev** [comment]
I mean toolbar, not page title.

**Comment by mail2bishnoi** [comment]
> 
> 
> I mean toolbar, not page title.

Sorry, but I didn't get which toolbar you are talking about.

**Comment by tananaev** [comment]
Each page has a toolbar (`MainToolbar` class). I'm not sure how you can miss it. It's on the top of each page.

**Comment by mail2bishnoi** [comment]
Now I understood. 
Yes, that can also be done and its advantage will be that we can set the title for each page. But for now, I only thought about the headings for the reports table.

I will implement the what you suggest.

**Comment by mail2bishnoi** [comment]
Should I proceed this or close the PR?

**Comment by tananaev** [comment]
Up to you. It would be nice to add title to the toolbar, but I don't think it's super urgent. If you go ahead, make sure it's a universal solution.

**Pull request closed without merging**
